import { ROLE, Status } from "@/types";

export type StaffType = {
	user: string;
	email: string;
	role: ROLE;
	created_at: string;
	status?: any;
};

export const staffData: StaffType[] = [
	{
		user: "Damilola Ogunsanya",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "active",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "Damilola Ogunsanya",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "active",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "staff",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
	{
		user: "John Omoseni",
		email: "customer@gmail.com",
		role: "admin",
		created_at: "01 Mar, 2024",
		status: "deactivated",
	},
];
